import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { api } from "~/utils/api";
import Image from "next/image";
import logo from "./logo.png";

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "WebNote User 👋" });

  return (
    <>
      <Head>
        <title>WebNote</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-stone-800 to-stone-500">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <Image priority src={logo} alt="logo" width={180} height={180}></Image>
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem] text-center">
            WebNote
          </h1>
          <div className="flex flex-col items-center gap-2">
            <p className="text-3xl text-white">
              {hello.data ? hello.data.greeting : "Loading..."}
            </p>
          </div>
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:gap-8">
            <Link
              className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20 border-2 border-red-500"
              href="https://chrome.google.com/webstore/category/extensions"
              target="_blank"
            >
              <h3 className="text-2xl font-bold">Get the Extension →</h3>
              <div className="text-lg">
                Install the one-click extension for creating full-page annotate-able screenshots!
              </div>
            </Link>
            <Link
              className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20 border-2 border-red-500"
              href="/editor"
            >
              <h3 className="text-2xl font-bold">Launch the editor →</h3>
              <div className="text-lg">
                Upload a picture manually and start annotating!
              </div>
            </Link>
          </div>
          <div className="flex flex-col items-center gap-2">
            <p className="text-sm text-white text-center">
              Made with ❤️
            </p>
            <p className="text-sm text-white text-center">
              Copyright © 2023 WebNote
            </p>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
